<?php
return array(
    'Home' => 'Accueil',
    'home' => 'accueil',
    'about' => 'à propos',
    'contact' => 'contact',
    'PREVIEW' => 'APERÇU',
    'I create awesome designs to stand out your site or product. Check some of my latest works' => 'Je crée de magnifiques designs pour faire ressortir votre site ou votre produit. Jeter un coup d\'œil à mes derniers travaux',
    'Welcome to my portfolio, my name is ' => 'Bienvenue sur mon portfolio, mon nom est ',
    'resume' => 'CV',
    'navigation' => 'navigation',
    'social links' => 'liens sociaux',
    'Contact Me' => 'Contactez Moi',
    'Download my resume' => 'Télécharger mon CV',
    'my skills' => 'mes compétences',
    'Most of my work are in' => 'La plupart de mes travaux sont en',
    'I also know about' => 'Je possède aussi des compétences en',
    'Let\'s Get In Touch' => 'Laissez moi un message',
    'name' => 'nom',
    'email' => 'email',
    'subject' => 'sujet',
    'message' => 'message',
    'submit' => 'soumettre',
    'The mail was successfully sent' => 'Le courriel a été envoyé avec succès',
    'The mail could not be sent' => 'Le courriel n\'a pas pu être envoyé',
    'A bit about me' => 'Mieux me connaître',
    'contacts' => '',
    'contacts' => '',
);
